### ISSUE TITLE
Set the rate and pitch of sound

### ISSUE THREAD

**Issue by LaunchingDream** [MikeyParton/react-speech-kit#10]
Hello. I'm Seunghyun from South Korea and front-end developer.
Thanks for your effort and contribution to this repository.

I wanna set the rate and pitch of sound.
I know the SpeechSynthesisUtterance interface of the Web Speech API can set the rate and pitch of the voice. How can I set them with 'react-speech-kit'?

Reference
- Pitch: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/pitch
- Rate: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/rate

**Comment by MikeyParton** [comment]
Hello. I haven't accounted for those options yet, but it looks like it should be pretty easy to add them in to the speak function together with the voice option. Leave it with me and I'll take a look at adding a PR.

https://github.com/MikeyParton/react-speech-kit/blob/a884a3b7894a2f41bc8b0b08f3501b34059950be/src/SpeechSynthesis.jsx#L53-L63

**Comment by LaunchingDream** [comment]
I Will. Thanks :)

**Comment by MikeyParton** [comment]
Thanks for the PR!
