### ISSUE TITLE
Calling speak function in useEffect doesn't work on mobile safari 

### ISSUE THREAD

**Issue by Snazzyham** [MikeyParton/react-speech-kit#14]
Not sure if this is the right place to ask about this, but I think its a mobile safari bug. 

I've got a function called playText() that runs in useEffect and it works fine on all browsers, except mobile safari. Any idea if there's a workaround that doesn't involve me tying it to a button click? 

Chrome allows it because it still plays only after the user interacts with the site. 

Additionally, onEnd isn't being consistently called on Desktop Safari. Sometimes it works, sometimes it doesn't, but it doesn't throw an error message or anything.

**Comment by Snazzyham** [comment]
Fixed this by moving playText out of useEffect, and just calling the function directly in the component body. To make sure it's not constantly running I used a state variable, so if !hasPlayed, play then set hasPlayed to true. 

Also, noticed that either this or mobile safari causes onEnd to not work. So I just moved that functionality to a timeout. 

Closing this issue, but thought I'd add this comment in case anyone else had the same problem. 

Sorry for not formatting my code, I'm on mobile.

**Comment by Himan-2000** [comment]
I am having a similar problem I want to readout "Welcome to (website name)" on loading of the react page but speak function is neither working in useEffect nor in window.onload.
Is there any work around?

**Comment by Himan-2000** [comment]
@Snazzyham can you pls help?

**Comment by pranshu1995** [comment]
I was having a similar issue with the 'listen' function (counterpart of speak).
My solution was to move the call from main useEffect (onLoad) to another one made specifically to start this function.

```
const [startListen, setStartListen] = useState(false);

useEffect(() => {
        setStartListen(true);
    }, [])

useEffect(() => {
        if(startListen){
            listen({interimResults: true, lang: "en-AU"});
            console.log("useEffecting3", listening);
        }
    }, [startListen])
```
