### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by nilsgoksor** [MikeyParton/react-speech-kit#24]
Trying to use this package on safari browsers gives the error `TypeError: null is not an object (evaluating 'recognition.current.lang = lang')`.

After doing some research on the issue I found that it's not supported https://caniuse.com/#search=SpeechRecognition. 

Is there any magic workaround? Do you guys have any idea when it might be fixed?

**Comment by MikeyParton** [comment]
Unfortunately there's no workaround at the moment. The speech recognition api is still experimental at this stage, so until Safari adds support you won't be able to use it. For the time being I would recommend using the [supported prop](https://github.com/MikeyParton/react-speech-kit#supported) before rendering any UI that controls speech recognition.
