### ISSUE TITLE
Is there any way to add commands 

### ISSUE THREAD

**Issue by sivajik34** [MikeyParton/react-speech-kit#26]
I would like to add commands like annyang js
Could you please create custom hook for annyang

**Comment by MikeyParton** [comment]
While there's nothing like that built directly into react-speech-kit, it should be pretty easy to implement some basic commands yourself. The idea would be to use the onResult function to store the result in state and then have your onEnd function try to find registered commands in the result. I haven't tested any of this, but it should be something along the lines of this

```jsx
const commands = {
    'show me the weather': () => {
       // do something
     }
  };

onEnd = () => {
   Object.keys(commands).forEach((command) => {
     if (result.indexOf(command)) {
       commands[command]();
     }
   })
}
```

At this stage I wouldn't consider this functionality that should be built into the library though.
