### ISSUE TITLE
Can't not npm i @type/react-speech-kit

### ISSUE THREAD

**Issue by GalaxyTea1** [MikeyParton/react-speech-kit#77]
I using typescript, npm ver: 6.14.13, react 17.0.2
I failed with err:

Could not find a declaration file for module 'react-speech-kit'. 'C:/Users/Admin/google-meet-clone/frontend/node_modules/react-speech-kit/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-speech-kit` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-speech-kit';`

I try npm i @type/react-speech-kit but it not working. Please help me!

**Comment by sankarkumar23** [comment]
Same issue here also. Please help.

**Comment by GalaxyTea1** [comment]
@sankarkumar23 I use react-spring instead of this library. I can't fix it 😄

**Comment by GalaxyTea1** [comment]
hmm i think lib not support typescript 😄

**Comment by morganney** [comment]
If you want TypeScript support for text-to-speech in React 18 you can try [tts-react](https://www.npmjs.com/package/tts-react).
