### ISSUE TITLE
react-speech-kit support in React-18?

### ISSUE THREAD

**Issue by fahadashiq12** [MikeyParton/react-speech-kit#79]
I am trying to install react-speech-kit in react-18 project but it didn't work out? Any alternatives to this library I want the specific section of my react application to implement text-to-speech functionality.

**Comment by fahadashiq12** [comment]
Note: The Project is in Typescript

**Comment by morganney** [comment]
@fahadashiq12 if you're looking for text-to-speech in React 18 with TypeScript you can try [tts-react](https://www.npmjs.com/package/tts-react). I've been developing it over the past couple of weeks but should be considered production ready.

**Comment by asadullahehsan** [comment]
> @fahadashiq12 if you're looking for text-to-speech in React 18 with TypeScript you can try [tts-react](https://www.npmjs.com/package/tts-react). I've been developing it over the past couple of weeks but should be considered production ready.

@morganney thanks. Even I was going to open this issue.

**Comment by asadullahehsan** [comment]
> I am trying to install react-speech-kit in react-18 project but it didn't work out? Any alternatives to this library I want the specific section of my react application to implement text-to-speech functionality.

@fahadashiq12 , Same here! Now I was going to open this issue
Actually they need to do two things
1. Give support for React version 18
2. Make a defined types file to support ts

**Comment by asadullahehsan** [comment]
@MikeyParton , please help us out with this issue. Thanks.

**Comment by gr1pcoding** [comment]
@asadullahehsan @fahadashiq12 
Hello all, I found myself here and figured out there's nothing in this package that won't work on React18. I installed the package with:
`npm install --legacy-peer-deps react-speech-kit`

**Comment by asadullahehsan** [comment]
@gr1pcoding , we can do that, no doubt. But would it be safe for the whole project in the long run? As there are already 5-6 more npm packages used in this project. This is not the only one package being used with React 18.

**Comment by gr1pcoding** [comment]
@asadullahehsan I didn't see any dependencies listed in package.json so it didn't seem to be an issue, the two source files don't import anything other than react. I'm just using this in a personal project though so hadn't given it much thought.

**Comment by rakibulinux** [comment]
I try with `npm install react-speech-kit -f` and it's working fine.

**Comment by fahadashiq12** [comment]
I guess this issue has been resolved closing this one.
